# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_squashed_0002_auto_20190120_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantownermap',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='restaurants.Restaurant'),
        ),
    ]
