# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.State'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Zip'),
        ),
    ]
