# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190118_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='city name'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='city pin code'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='state name'),
        ),
    ]
