# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IP', 'in progress'), ('DP', 'dispatched'), ('DL', 'delivered'), ('CL', 'cancelled')], default='IP', max_length=2)),
                ('items', models.ManyToManyField(related_name='in_orders', related_query_name='in_orders', to='restaurants.Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
