# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('orders', '0002_auto_20190116_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_order', to='restaurants.Menu'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together=set([('item', 'order')]),
        ),
    ]
