# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190116_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
