# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190120_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'placed'), (2, 'in progress'), (1, 'accepted'), (3, 'dispatched'), (4, 'delivered'), (5, 'cancelled'), (6, 'rejected')], default=0),
        ),
    ]
